name: Build Squirrel.Windows

on: workflow_dispatch

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: NuGet restore
      run: .\.NuGet\NuGet.exe restore

    - name: MsBuild
      run: msbuild /p:Configuration=Release      
